blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://thomas-rauter.github.io/kpnn2/
    about: Read the kpnn2 documentation.
  - name: GitHub Discussions
    url: https://github.com/Thomas-Rauter/kpnn2/discussions
    about: Ask open-ended questions or discuss ideas.
